name: Labeler

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'TanStack'
    steps:
      - uses: actions/labeler@v4.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
